### PR TITLE
completes #93, correcting website links

### PR DESCRIPTION
**Pull request by ltmetz**
Updated website links for CBRS Mapper. Found a couple more that were not in the document that were part of a tooltip and went ahead and updated those too. I think all corrections are made!

### CODE REVIEW

**Review by lprivette — APPROVED** [review]

**Comment by lprivette** [comment]
@ltmetz can you increment the version and then create a release for it once it's merged into master?

**Comment by ltmetz** [comment]
I have never incremented the version or created a release. I see notes on versioning and maybe can figure that out, but I am not sure what to do about the "create a release" part. lol

**Comment by lprivette** [comment]
You can just change the code.json to 2.1.4 which it's already at for some reason lol. Should also update that in the package.json and bower.json as well. 

Once that's done you click the '+ # releases' button

image

Draft a new release: 
image

for the tag type in 2.1.4 and target of master, give it a title (I usually just call it the version number like 'v2.1.4'), quick description of the changes, and publish release.

Once you let me know you've seen this I'll approve the PR and you can just make the version changes to the code/package/bower.json directly to master (unless you want to do it differently)

Creating releases is nice because it gives us a snapshot and paper trail of what precisely was deployed in each update to prod

**Comment by ltmetz** [comment]
Okay, cool. I just updated the version in all those places. And then I can do a release! Thank you!

**Pull request merged**
